map:
    name: IMS ## マップの名前
    ext: .png ## マップの拡張子
    speed: 5.0 ## waypointの速度
    downsample: 1 ## マップのダウンサンプリング
timestep: 0.01 ## シミュレータの時間間隔
num_beams: 1080 ## 2d Lidarのビーム数
beam_fov: 4.7 ## 2d Lidarの範囲 -270° ~ 270°
num_agents: 1
render_mode: human_fast ## human or human_fast