map:
    name: IMS ## マップの名前
    ext: .png ## マップの拡張子
    line_type: center ## center race
    speed: 5.0 ## waypointの速度
    downsample: 1 ## マップのダウンサンプリング

    ## planner用の設定
    use_dynamic_speed: false ## 動的な速度を使用するかどうか
    a_lat_max: 1.0 ## 最大横加速度
    smooth_sigma: 3 ## スムージングのsigma


timestep: 0.01 ## シミュレータの時間間隔
num_beams: 1080 ## 2d Lidarのビーム数
beam_fov: 4.7 ## 2d Lidarの範囲 -270° ~ 270°
num_agents: 1
render_mode: human_fast ## human or human_fast