defaults:
  - vehicle: default
  - envs: default 
  - reward: ???
  - agent: ???


ckpt_path: ???  # 評価に使うモデル
num_eval_episodes: 1
save_csv_dir: ./outputs/eval/trajectories/${now:%Y-%m-%d}

hydra:
  run:
    dir: ./outputs/eval/${now:%Y-%m-%d}/${now:%H-%M-%S}