name: PPO
lr: 3e-4
gamma: 0.99
lam: 0.95
clip_eps: 0.2
ppo_epochs: 10
value_coef: 0.5
entropy_coef: 0.01
backbone:
  name: mlp ## tiny_lider_net or mlp
  input_dim: 120
  k_frames: 2 ## 2フレーム間の情報を使う
  downsample_n: 60 ## 1080 -> 60
ckpt_path: null